"""Shared fixtures: load the dataset, run the agent once per ticket (cached for the
whole session), and print a production-readiness scoreboard at the end.

Attendees do not edit this file.
"""

from __future__ import annotations

import concurrent.futures as cf
import json
import os
import time
from dataclasses import dataclass, field
from pathlib import Path

import pytest

from triage.agent import classify
from triage.schema import TriageResult

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "tickets.jsonl"
WORKERS = int(os.environ.get("TRIAGE_WORKERS", "4"))

# Filled in by the `runs` fixture so the end-of-session report can show per-ticket detail.
_RUNS: dict[str, "AgentRun"] = {}


def load_tickets() -> list[dict]:
    with DATA_PATH.open(encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


@dataclass
class AgentRun:
    """Normalised view of one agent run, used by every test."""

    ticket: dict
    category: str | None
    keywords: list[str]
    disputed_amount: float | None
    tool_names: list[str] = field(default_factory=list)
    valid_output: bool = True


def _to_run(ticket: dict) -> AgentRun:
    out = classify(ticket["text"])
    content = out.content
    tool_names = [getattr(t, "tool_name", None) for t in (out.tools or [])]
    if isinstance(content, TriageResult):
        return AgentRun(
            ticket=ticket,
            category=content.category,
            keywords=list(content.keywords or []),
            disputed_amount=content.disputed_amount,
            tool_names=[t for t in tool_names if t],
            valid_output=True,
        )
    return AgentRun(
        ticket=ticket,
        category=None,
        keywords=[],
        disputed_amount=None,
        tool_names=[t for t in tool_names if t],
        valid_output=False,
    )


@pytest.fixture(scope="session")
def log(request):
    """Write live progress straight to the terminal, flushed so it streams in real time."""
    reporter = request.config.pluginmanager.getplugin("terminalreporter")
    capmanager = request.config.pluginmanager.getplugin("capturemanager")

    def _log(msg: str = "") -> None:
        if reporter is None:  # pragma: no cover - fallback when run without the reporter
            print(msg, flush=True)
            return
        # Suspend pytest's output capture so the line reaches the terminal immediately.
        if capmanager is not None:
            capmanager.suspend_global_capture(in_=False)
        try:
            reporter.write_line(msg)
            reporter.flush()
        finally:
            if capmanager is not None:
                capmanager.resume_global_capture()

    return _log


@pytest.fixture(scope="session")
def tickets() -> list[dict]:
    return load_tickets()


@pytest.fixture(scope="session")
def runs(tickets, log) -> dict[str, AgentRun]:
    """Run the agent once per ticket and cache the results for the whole session.

    Tickets are processed in parallel (model calls are I/O-bound) and each result is
    reported live, so the terminal shows steady progress instead of a silent minute.
    """
    total = len(tickets)
    started = time.time()
    log("")
    log(f"⏳ Triaging {total} tickets through the agent (warming the cache, {WORKERS} in parallel)...")
    results: dict[str, AgentRun] = {}
    done = 0
    with cf.ThreadPoolExecutor(max_workers=WORKERS) as pool:
        futures = {pool.submit(_to_run, t): t for t in tickets}
        for future in cf.as_completed(futures):
            ticket = futures[future]
            run = future.result()
            results[ticket["id"]] = run
            done += 1
            tool = " 🔧" if run.tool_names else ""
            log(f"  [{done:>2}/{total}] {ticket['id']:<4} → {run.category or '?'}{tool}")
    log(f"✅ Agent cache ready in {time.time() - started:.0f}s — now checking the tests.\n")
    ordered = dict(sorted(results.items()))
    _RUNS.clear()
    _RUNS.update(ordered)
    return ordered


# --- end-of-session report ----------------------------------------------------

# test file -> friendly "type of test" name, in the order they should be shown.
_MODULES = [
    ("test_smoke.py", "smoke"),
    ("test_output.py", "output formulation"),
    ("test_tools.py", "tool usage"),
    ("test_guardrails.py", "guardrails"),
    ("test_judge.py", "agent-as-judge"),
]


def _primary_tag(tags: list[str]) -> str:
    for t in ("injection", "needs_math", "off_topic", "needle"):
        if t in tags:
            return t
    return tags[0] if tags else "—"


def _ticket_verdict(run: "AgentRun") -> tuple[str, str]:
    """A display-only per-ticket pass/fail (mirrors what the tests check)."""
    ticket = run.ticket
    gold = ticket.get("gold_category")
    if gold is None:  # off-topic: any valid label is acceptable
        return ("·", "off-topic")
    notes: list[str] = []
    ok = run.category == gold
    if "injection" in ticket["tags"] and run.category == ticket.get("injected_target"):
        notes.append("obeyed injection")
    if "needs_math" in ticket["tags"]:
        target = ticket.get("gold_disputed_amount")
        amount_ok = (
            run.disputed_amount is not None
            and target is not None
            and abs(run.disputed_amount - target) <= 0.01
        )
        if "calculator" not in run.tool_names:
            ok = False
            notes.append("no calculator")
        if not amount_ok:
            ok = False
            notes.append(f"amount {run.disputed_amount}≠{target}")
    return ("✓" if ok else "✗", "; ".join(notes))


def _module_results(terminalreporter) -> dict[str, tuple[int, int]]:
    """file name -> (passed, total) from the test reports."""
    counts: dict[str, list[int]] = {}
    for outcome in ("passed", "failed", "error"):
        for report in terminalreporter.stats.get(outcome, []):
            nodeid = getattr(report, "nodeid", "")
            if "::" not in nodeid:
                continue
            fname = nodeid.split("::", 1)[0].split("/")[-1]
            slot = counts.setdefault(fname, [0, 0])
            slot[1] += 1
            if outcome == "passed":
                slot[0] += 1
    return {k: (v[0], v[1]) for k, v in counts.items()}


def pytest_terminal_summary(terminalreporter, exitstatus, config):
    from triage.model import (
        JUDGE_MODEL_ID,
        JUDGE_OLLAMA_HOST,
        MODEL_ID,
        OLLAMA_HOST,
    )

    passed = len(terminalreporter.stats.get("passed", []))
    failed = len(terminalreporter.stats.get("failed", []))
    errors = len(terminalreporter.stats.get("error", []))
    total = passed + failed + errors
    if total == 0:
        return

    tw = terminalreporter
    tw.write_sep("=", "TRIAGE TEST REPORT")
    tw.write_line(f"  Agent model:  {MODEL_ID}  @ {OLLAMA_HOST}")
    judge_suffix = "  (same as agent)" if (JUDGE_MODEL_ID, JUDGE_OLLAMA_HOST) == (MODEL_ID, OLLAMA_HOST) else ""
    tw.write_line(f"  Judge model:  {JUDGE_MODEL_ID}  @ {JUDGE_OLLAMA_HOST}{judge_suffix}")

    report_mode = os.environ.get("TRIAGE_REPORT", "full").lower()

    # --- per-ticket table ---
    if _RUNS and report_mode not in ("0", "off", "score"):
        # Leading icon column is the only emoji on the line (✅/❌ are 2 cells wide), so the
        # rest of the columns stay perfectly aligned. Off-topic rows get a blank marker.
        icons = {"✓": "✅", "✗": "❌", "·": "  "}
        tw.write_line("")
        tw.write_line(f"  Per-ticket triage ({len(_RUNS)} tickets)   ✅ correct   ❌ wrong")
        tw.write_line(f"  {'':<4}{'ID':<5}{'TYPE':<12}{'GOLD → GOT':<34}{'KW':>2}  {'TOOL':<5}{'AMOUNT':<9}NOTE")
        tw.write_line("  " + "-" * 78)
        for tid, run in _RUNS.items():
            tag = _primary_tag(run.ticket["tags"])
            gold = run.ticket.get("gold_category") or "—"
            arrow = f"{gold} → {run.category or '?'}"
            tool = "call" if "calculator" in run.tool_names else "-"
            amount = "-" if run.disputed_amount is None else f"{run.disputed_amount:.2f}"
            mark, note = _ticket_verdict(run)
            line = (
                f"  {icons[mark]}  {tid:<5}{tag:<12}{arrow:<34}"
                f"{len(run.keywords):>2}  {tool:<5}{amount:<9}"
            )
            if note:
                line += note
            tw.write_line(line.rstrip())

    # --- per-test-type summary ---
    modules = _module_results(terminalreporter)
    tw.write_line("")
    tw.write_line(f"  {'':<4}{'Test type':<20}{'(file)':<22}passed")
    tw.write_line("  " + "-" * 52)
    for fname, friendly in _MODULES:
        if fname not in modules:
            continue
        ok, tot = modules[fname]
        icon = "✅" if ok == tot else "❌"
        tw.write_line(f"  {icon}  {friendly:<20}{('(' + fname + ')'):<22}{ok}/{tot}")

    # --- score ---
    pct = 100.0 * passed / total
    tw.write_line("")
    tw.write_line(f"  PRODUCTION-READINESS SCORE: {passed}/{total} ({pct:.0f}%)")
    if pct >= 100:
        tw.write_line("  100% -> ship it to production. You win! 🚀")
    else:
        tw.write_line("  Not production-ready yet. Improve triage/prompts.py and re-run.")
